# -*- coding: utf-8 -*-
"""BinarySearch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fGB5oATRC4mO-WJ5IIgFLzOm5Natvw5V
"""

def binary_search(arr, l, r, key):

    if l <= r:

      mid = (l + r) // 2

      if arr[mid] == key:
        return mid

      elif arr[mid] > key:
        return binary_search(arr, l, mid - 1, key)

      else:
        return binary_search(arr, mid + 1, r, key)

    else:
      return None

a = [1, 2, 5, 4, 10, 11, 12, 15, 23, 32, 41, 54, 61, 72, 92, 100]
print(binary_search(a, 0, len(a)-1, 12))